package com.google.mediapipe.examples.facelandmarker.fragment

import android.Manifest
import android.content.pm.PackageManager
import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.activity.result.contract.ActivityResultContracts
import androidx.camera.core.AspectRatio
import androidx.camera.core.Camera
import androidx.camera.core.CameraSelector
import androidx.camera.core.ImageAnalysis
import androidx.camera.core.ImageProxy
import androidx.camera.core.Preview
import androidx.camera.lifecycle.ProcessCameraProvider
import androidx.core.content.ContextCompat
import androidx.fragment.app.Fragment
import androidx.fragment.app.activityViewModels
import com.google.mediapipe.examples.facelandmarker.FaceLandmarkerHelper
import com.google.mediapipe.examples.facelandmarker.MainViewModel
import com.google.mediapipe.examples.facelandmarker.databinding.FragmentCameraBinding
import com.google.mediapipe.tasks.vision.core.RunningMode
import java.util.concurrent.ExecutorService
import java.util.concurrent.Executors

class CameraFragment : Fragment(), FaceLandmarkerHelper.LandmarkerListener {

    companion object {
            private const val TAG = "FaceBlurCamera"
                }

                    private var _binding: FragmentCameraBinding? = null
                        private val binding get() = _binding!!

                            private val viewModel: MainViewModel by activityViewModels()
                                private lateinit var faceLandmarkerHelper: FaceLandmarkerHelper

                                    private var preview: Preview? = null
                                        private var imageAnalyzer: ImageAnalysis? = null
                                            private var camera: Camera? = null
                                                private var cameraProvider: ProcessCameraProvider? = null
                                                    private var cameraFacing = CameraSelector.LENS_FACING_FRONT

                                                        private lateinit var backgroundExecutor: ExecutorService

                                                            private val permissionLauncher =
                                                                    registerForActivityResult(ActivityResultContracts.RequestPermission()) { granted ->
                                                                                if (granted) setUpCamera() else Log.e(TAG, "Camera permission denied")
                                                                                        }

                                                                                            override fun onCreateView(
                                                                                                    inflater: LayoutInflater,
                                                                                                            container: ViewGroup?,
                                                                                                                    savedInstanceState: Bundle?
                                                                                                                        ): View {
                                                                                                                                _binding = FragmentCameraBinding.inflate(inflater, container, false)
                                                                                                                                        return binding.root
                                                                                                                                            }

                                                                                                                                                override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
                                                                                                                                                        super.onViewCreated(view, savedInstanceState)
                                                                                                                                                                backgroundExecutor = Executors.newSingleThreadExecutor()

                                                                                                                                                                        // Create the landmarker off the main thread
                                                                                                                                                                                backgroundExecutor.execute {
                                                                                                                                                                                            faceLandmarkerHelper = FaceLandmarkerHelper(
                                                                                                                                                                                                            context = requireContext(),
                                                                                                                                                                                                                            runningMode = RunningMode.LIVE_STREAM,
                                                                                                                                                                                                                                            minFaceDetectionConfidence = viewModel.currentMinFaceDetectionConfidence,
                                                                                                                                                                                                                                                            minFaceTrackingConfidence = viewModel.currentMinFaceTrackingConfidence,
                                                                                                                                                                                                                                                                            minFacePresenceConfidence = viewModel.currentMinFacePresenceConfidence,
                                                                                                                                                                                                                                                                                            maxNumFaces = viewModel.currentMaxFaces,
                                                                                                                                                                                                                                                                                                            currentDelegate = viewModel.currentDelegate,
                                                                                                                                                                                                                                                                                                                            faceLandmarkerHelperListener = this
                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                        binding.viewFinder.post {
                                                                                                                                                                                                                                                                                                                                                                    if (ContextCompat.checkSelfPermission(
                                                                                                                                                                                                                                                                                                                                                                                        requireContext(), Manifest.permission.CAMERA
                                                                                                                                                                                                                                                                                                                                                                                                        ) == PackageManager.PERMISSION_GRANTED
                                                                                                                                                                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    setUpCamera()
                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                permissionLauncher.launch(Manifest.permission.CAMERA)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private fun setUpCamera() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    val future = ProcessCameraProvider.getInstance(requireContext())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            future.addListener({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cameraProvider = future.get()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bindCameraUseCases()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, ContextCompat.getMainExecutor(requireContext()))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    private fun bindCameraUseCases() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            val provider = cameraProvider ?: return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    val rotation = binding.viewFinder.display.rotation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            val selector = CameraSelector.Builder().requireLensFacing(cameraFacing).build()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    preview = Preview.Builder()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .setTargetAspectRatio(AspectRatio.RATIO_4_3)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setTargetRotation(rotation)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .build()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                imageAnalyzer = ImageAnalysis.Builder()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setTargetAspectRatio(AspectRatio.RATIO_4_3)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .setTargetRotation(rotation)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .setOutputImageFormat(ImageAnalysis.OUTPUT_IMAGE_FORMAT_RGBA_8888)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .build()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .also { it.setAnalyzer(backgroundExecutor) { image -> detectFace(image) } }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                provider.unbindAll()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    camera = provider.bindToLifecycle(this, selector, preview, imageAnalyzer)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                preview?.setSurfaceProvider(binding.viewFinder.surfaceProvider)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (e: Exception) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Log.e(TAG, "Camera binding failed", e)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    private fun detectFace(imageProxy: ImageProxy) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!::faceLandmarkerHelper.isInitialized) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        imageProxy.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    faceLandmarkerHelper.detectLiveStream(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                imageProxy = imageProxy,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isFrontCamera = cameraFacing == CameraSelector.LENS_FACING_FRONT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            override fun onResults(resultBundle: FaceLandmarkerHelper.ResultBundle) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    activity?.runOnUiThread {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _binding?.overlay?.let {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                it.setResults(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    resultBundle.result,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        resultBundle.inputImageHeight,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            resultBundle.inputImageWidth,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                RunningMode.LIVE_STREAM
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                it.invalidate()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            override fun onError(error: String, errorCode: Int) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Log.e(TAG, "Landmarker error $errorCode: $error")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            override fun onDestroyView() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    super.onDestroyView()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _binding = null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cameraProvider?.unbindAll()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (::faceLandmarkerHelper.isInitialized) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundExecutor.execute { faceLandmarkerHelper.clearFaceLandmarker() }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundExecutor.shutdown()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
